; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Money"
#define MyAppVersion "1.5"
#define MyAppPublisher "WRServices"
#define MyAppURL "wadsonwadson@hotmail.com"
#define MyAppExeName "Money.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E19DBA22-8A9E-4116-98CC-2FD5385B0B5C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:\Users\WR Services\Desktop\Money
OutputBaseFilename=setup
SetupIconFile=C:\Money\ìcone WR6.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\WR Services\Desktop\Money\Money.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\bdfinanca.sdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\Exemplo.docx"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\Money.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\Rel_Contas_Periodo.rdlc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\Rel_Contas_por_Forn_and_Venc.rdlc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\Rel_Contas_por_Fornecedor.rdlc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\Rel_Contas_por_Situacao.rdlc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\Rel_Fornecedor.rdlc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\Rel_Periodo.rdlc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\WR Services\Desktop\Money\System.Data.SqlServerCe.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

